require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/seasons", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Season. As you add validations to Season, be sure to
  # adjust the attributes here as well.
  let(:org) { create(:organization) }
  let(:valid_attributes) { { title: "Season", organization_id: org.id } }
  let!(:season) { create(:season, valid_attributes) }
  let(:invalid_attributes) { { title: "", organization_id: org.id } }
  let!(:invalid_season) { build(:season, invalid_attributes) }

  describe "GET /index" do
    it "renders a successful response" do
      get seasons_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      get season_url(season)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_season_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      get edit_season_url(season)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Season" do
        expect {
          post seasons_url, params: { season: valid_attributes }
        }.to change(Season, :count).by(1)
      end

      it "redirects to the created season" do
        post seasons_url, params: { season: valid_attributes }
        expect(response).to redirect_to(season_url(Season.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Season" do
        expect {
          post seasons_url, params: { season: invalid_attributes }
        }.to change(Season, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post seasons_url, params: { season: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        { title: "New Season" }
      }

      it "updates the requested season" do
        patch season_url(season), params: { season: new_attributes }
        season.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the season" do
        patch season_url(season), params: { season: new_attributes }
        season.reload
        expect(response).to redirect_to(season_url(season))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        patch season_url(season), params: { season: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested season" do
      expect {
        delete season_url(season)
      }.to change(Season, :count).by(-1)
    end

    it "redirects to the seasons list" do
      delete season_url(season)
      expect(response).to redirect_to(seasons_url)
    end
  end
end
